# Generated by Django 3.0.8 on 2020-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catagory', models.CharField(default='unknown', max_length=50)),
                ('pic', models.ImageField(upload_to='wallpaper')),
            ],
        ),
    ]
